Use sys;
CREATE TABLE DEPT (
    DEPTNO INT PRIMARY KEY,
    DNAME VARCHAR(50),
    LOC VARCHAR(50)
);

ALTER TABLE DEPT
RENAME TO DEPARTMENT;

ALTER TABLE DEPARTMENT
ADD PINCODE VARCHAR(10) NOT NULL;

ALTER TABLE DEPARTMENT
RENAME COLUMN DNAME TO DEPT_NAME;

ALTER TABLE DEPARTMENT
MODIFY LOC CHAR(10);

DROP TABLE DEPARTMENT;

SELECT * FROM DEPT;